apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flask-crud-chart.fullname" . }}-mysql-secret
  labels:
  {{- include "flask-crud-chart.labels" . | nindent 4 }}
data:
  MYSQL_ROOT_PASSWORD: {{ required "mysqlSecret.mysqlRootPassword is required" .Values.mysqlSecret.mysqlRootPassword
    | b64enc | quote }}
type: Opaque
